<a href="https://colab.research.google.com/github/prithvee2k4/DSAB13-CaseStudy/blob/main/Case_Study_numpy_pandas_Prithvi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#read_csv(filepath)
import pandas as pd
import numpy as np

filepath ='https://raw.githubusercontent.com/laxmimerit/All-CSV-ML-Data-Files-Download/master/IMDB-Movie-Data.csv'
df = pd.read_csv(filepath)
df

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [29]:
# Shape
print("Shape of dataset:")
print(df.shape)
print("\n")

# First 5 rows
print("\nFirst 5 rows:")
print(df.head())
print("\n")

# Column names
print("\nColumn names:")
print(df.columns)
print("\n")

# Data types
print("\nData types:")
print(df.dtypes)
print("\n")

# Missing values
print("\nMissing values:")
print(df.isnull().sum())
print("\n")

# 4) To Check and remove duplicates.

# Check number of duplicate rows
print("\nNumber of duplicate rows:")
print(df.duplicated().sum())
print("\n")

# Remove duplicates
df = df.drop_duplicates()

print("\nShape after removing duplicates:")
print(df.shape)
print("\n")

# 5) Rename column "Title" to "Movie_Title"

df.rename(columns={'Title': 'Movie_Title'}, inplace=True)

print("\nColumns after renaming:")
print(df.columns)
print("\n")

# 6) Get unique genres.

print("\nUnique Genres:")
print(df['Genre'].unique())
print("\n")

# 7) Extract number of genres per movie

print(df['Genre'].str.split(',').str.len())
print("\n")
print()

#OR

print(df[['Movie_Title', 'Genre']].assign(
    Number_of_Genres=df['Genre'].str.split(',').str.len()))
print()

# 8)  Handle missing values in 'Revenue (Millions)' and 'Metascore.

df['Revenue (Millions)'] = df['Revenue (Millions)'].fillna(df['Revenue (Millions)'].mean()) # fillna() - Use to replace/handle missing values.

df['Metascore'] = df['Metascore'].fillna(df['Metascore'].mean())

print(df.isnull().sum())
print()

# 9) Top 5 movies by Rating.

top5 = df.sort_values('Rating', ascending=False).head(5)

print(top5[['Movie_Title', 'Rating']])

print()

# 10) Movie with highest revenue

highest = df.sort_values('Revenue (Millions)', ascending=False).head(1)
print("Movie with highest and lowest revenue: ")

print(highest[['Movie_Title', 'Revenue (Millions)']])
print()

# Movie with lowest revenue.

lowest = df.sort_values('Revenue (Millions)').head(1)
print("Movie with highest and lowest revenue: ")

print(lowest[['Movie_Title', 'Revenue (Millions)']])
print()

#11) Average rating by Director.

avg_rating = df.groupby('Director')['Rating'].mean()
print("Average rating by Director: ")
print()
print(avg_rating)
print()

#12) Movies per year.

movies_year = df.groupby('Year')['Movie_Title'].count()
print("Movies per year: ")
print()
print(movies_year)
print()

#13)  Movies with rating > 8 & revenue > 100M

result = df[(df['Rating'] > 8) & (df['Revenue (Millions)'] > 100)]
print("Movies with rating > 8 & revenue > 100M: ")
print()
print(result[['Movie_Title', 'Rating', 'Revenue (Millions)']])
print()

#14) Group by Director: avg Rating, Revenue.

director_group = df.groupby('Director')[['Rating', 'Revenue (Millions)']].mean()
print("Group by Director: avg Rating, Revenue: ")
print()
print(director_group)
print()

#15)  Group by Year: count, avg Rating.

year_group = df.groupby('Year')[['Rating']].agg(['count', 'mean']) # Performs multiple calculation on 'Rating' column.
print("Group by Year: count, avg Rating: ")
print()
print(year_group)
print()

#16) Create a new column Profitability:
# a) Revenue divided by Duration.

df['Profitability'] = df['Revenue (Millions)'] / df['Runtime (Minutes)']
print("New column Profitability: ")
print()
print(df[['Movie_Title', 'Profitability']])
print()



top10 = df.sort_values('Profitability', ascending=False).head(10)
print("Top 10 most profitable movies: ")
print()
print(top10[['Movie_Title', 'Profitability']])
print()

Shape of dataset:
(1000, 12)



First 5 rows:
   Rank              Movie_Title                     Genre  \
0     1  Guardians of the Galaxy   Action,Adventure,Sci-Fi
1     2               Prometheus  Adventure,Mystery,Sci-Fi
2     3                    Split           Horror,Thriller
3     4                     Sing   Animation,Comedy,Family
4     5            Suicide Squad  Action,Adventure,Fantasy

                                         Description              Director  \
0  A group of intergalactic criminals are forced ...            James Gunn
1  Following clues to the origin of mankind, a te...          Ridley Scott
2  Three girls are kidnapped by a man with a diag...    M. Night Shyamalan
3  In a city of humanoid animals, a hustling thea...  Christophe Lourdelet
4  A secret government agency recruits some of th...            David Ayer

                                              Actors  Year  Runtime (Minutes)  \
0  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014                121
1  Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012                124
2  James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016                117
3  Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016                108
4  Will Smith, Jared Leto, Margot Robbie, Viola D...  2016                123

   Rating   Votes  Revenue (Millions)  Metascore
0     8.1  757074              333.13       76.0
1     7.0  485820              126.46       65.0
2     7.3  157606              138.12       62.0
3     7.2   60545              270.32       59.0
4     6.2  393727              325.02       40.0



Column names:
Index(['Rank', 'Movie_Title', 'Genre', 'Description', 'Director', 'Actors',
       'Year', 'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')



Data types:
Rank                    int64
Movie_Title            object
Genre                  object
Description            object
Director               object
Actors                 object
Year                    int64
Runtime (Minutes)       int64
Rating                float64
Votes                   int64
Revenue (Millions)    float64
Metascore             float64
dtype: object



Missing values:
Rank                  0
Movie_Title           0
Genre                 0
Description           0
Director              0
Actors                0
Year                  0
Runtime (Minutes)     0
Rating                0
Votes                 0
Revenue (Millions)    0
Metascore             0
dtype: int64



Number of duplicate rows:
0



Shape after removing duplicates:
(1000, 12)



Columns after renaming:
Index(['Rank', 'Movie_Title', 'Genre', 'Description', 'Director', 'Actors',
       'Year', 'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')



Unique Genres:
['Action,Adventure,Sci-Fi' 'Adventure,Mystery,Sci-Fi' 'Horror,Thriller'
 'Animation,Comedy,Family' 'Action,Adventure,Fantasy' 'Comedy,Drama,Music'
 'Comedy' 'Action,Adventure,Biography' 'Adventure,Drama,Romance'
 'Adventure,Family,Fantasy' 'Biography,Drama,History'
 'Animation,Adventure,Comedy' 'Action,Comedy,Drama' 'Action,Thriller'
 'Biography,Drama' 'Drama,Mystery,Sci-Fi' 'Adventure,Drama,Thriller'
 'Drama' 'Crime,Drama,Horror' 'Action,Adventure,Drama' 'Drama,Thriller'
 'Action,Adventure,Comedy' 'Action,Horror,Sci-Fi' 'Adventure,Drama,Sci-Fi'
 'Action,Adventure,Western' 'Comedy,Drama' 'Horror'
 'Adventure,Drama,Fantasy' 'Action,Crime,Thriller' 'Action,Crime,Drama'
 'Adventure,Drama,History' 'Crime,Horror,Thriller' 'Drama,Romance'
 'Comedy,Drama,Romance' 'Horror,Mystery,Thriller' 'Crime,Drama,Mystery'
 'Drama,Romance,Thriller' 'Drama,History,Thriller' 'Action,Drama,Thriller'
 'Drama,History' 'Action,Drama,Romance' 'Drama,Fantasy' 'Action,Sci-Fi'
 'Adventure,Drama,War' 'Action,Comedy,Fantasy' 'Biography,Comedy,Crime'
 'Crime,Drama' 'Comedy,Crime,Drama' 'Action,Comedy,Crime'
 'Animation,Drama,Fantasy' 'Horror,Mystery,Sci-Fi'
 'Drama,Mystery,Thriller' 'Crime,Drama,Thriller' 'Biography,Crime,Drama'
 'Crime,Mystery,Thriller' 'Action,Horror,Thriller' 'Romance,Sci-Fi'
 'Action,Fantasy,War' 'Action,Biography,Drama' 'Drama,Horror,Mystery'
 'Adventure,Drama,Family' 'Adventure,Comedy,Romance' 'Action'
 'Adventure,Crime,Mystery' 'Comedy,Family,Musical'
 'Adventure,Comedy,Drama' 'Drama,Horror,Thriller' 'Drama,Music'
 'Mystery,Thriller' 'Mystery,Thriller,Western' 'Comedy,Family'
 'Biography,Comedy,Drama' 'Drama,Western' 'Drama,Mystery,Romance'
 'Action,Drama,Mystery' 'Action,Adventure,Crime'
 'Adventure,Sci-Fi,Thriller' 'Action,Comedy,Mystery' 'Thriller,War'
 'Action,Adventure,Thriller' 'Drama,Fantasy,Romance'
 'Action,Drama,History' 'Animation,Adventure,Family' 'Adventure,Horror'
 'Drama,Romance,Sci-Fi' 'Action,Adventure,Family' 'Action,Comedy'
 'Comedy,Romance' 'Horror,Mystery' 'Drama,Family,Fantasy' 'Sci-Fi'
 'Drama,War' 'Drama,Fantasy,Horror' 'Crime,Drama,History'
 'Horror,Sci-Fi,Thriller' 'Action,Drama,Sport' 'Adventure,Biography,Drama'
 'Biography,Drama,Thriller' 'Action,Adventure,Mystery' 'Drama,Horror'
 'Comedy,Crime' 'Drama,Fantasy,War' 'Action,Adventure,Romance'
 'Action,Drama,War' 'Drama,Musical,Romance' 'Drama,Sci-Fi,Thriller'
 'Action,Drama,Sci-Fi' 'Drama,Sci-Fi' 'Adventure,Fantasy' 'Thriller'
 'Biography,Drama,Romance' 'Action,Adventure' 'Action,Fantasy'
 'Action,Drama,Horror' 'Comedy,Music,Romance' 'Biography,Drama,Sport'
 'Action,Horror' 'Comedy,Horror,Thriller' 'Crime,Drama,Music'
 'Action,Sci-Fi,Thriller' 'Drama,Horror,Sci-Fi' 'Drama,Sport'
 'Comedy,Horror' 'Comedy,Fantasy,Romance' 'Comedy,Fantasy'
 'Comedy,Drama,Fantasy' 'Adventure,Comedy,Horror' 'Comedy,Mystery'
 'Action,Mystery,Sci-Fi' 'Action,Crime,Fantasy' 'Comedy,Fantasy,Horror'
 'Animation,Action,Adventure' 'Action,Comedy,Family' 'Comedy,Sci-Fi'
 'Action,Biography,Crime' 'Adventure,Comedy' 'Comedy,Music'
 'Comedy,Drama,Horror' 'Action,Horror,Romance' 'Action,Drama,Fantasy'
 'Action,Mystery,Thriller' 'Action,Adventure,Horror'
 'Animation,Family,Fantasy' 'Adventure,Horror,Mystery'
 'Action,Horror,Mystery' 'Adventure,Comedy,Family' 'Action,Crime,Mystery'
 'Comedy,Drama,Family' 'Action,Crime,Sport' 'Mystery,Sci-Fi,Thriller'
 'Sci-Fi,Thriller' 'Adventure,Drama,Horror' 'Biography,History,Thriller'
 'Adventure,Comedy,Sci-Fi' 'Fantasy,Horror' 'Action,Fantasy,Thriller'
 'Comedy,Romance,Sport' 'Animation,Action,Comedy' 'Drama,Fantasy,Thriller'
 'Action,Comedy,Romance' 'Action,Fantasy,Horror' 'Mystery,Romance,Sci-Fi'
 'Comedy,Drama,Thriller' 'Comedy,Western' 'Drama,History,War'
 'Fantasy,Horror,Thriller' 'Drama,Horror,Musical' 'Drama,Family'
 'Romance,Sci-Fi,Thriller' 'Animation,Fantasy' 'Drama,Mystery,War'
 'Action,Drama,Family' 'Adventure,Drama,Western' 'Drama,Music,Romance'
 'Comedy,Romance,Western' 'Adventure,Drama' 'Drama,Thriller,War'
 'Drama,Fantasy,Mystery' 'Comedy,Crime,Thriller' 'Animation,Comedy,Drama'
 'Action,Comedy,Sci-Fi' 'Drama,Romance,War' 'Adventure,Fantasy,Mystery'
 'Mystery,Romance,Thriller' 'Biography,Drama,Mystery'
 'Animation,Drama,Romance' 'Comedy,Horror,Romance' 'Action,Thriller,War'
 'Action,Comedy,Horror' 'Action,Crime,Sci-Fi' 'Crime,Thriller'
 'Comedy,Horror,Sci-Fi' 'Crime,Drama,Fantasy' 'Drama,Fantasy,Music'
 'Action,Comedy,Sport' 'Fantasy,Mystery,Thriller' 'Adventure'
 'Adventure,Biography' 'Adventure,Biography,Crime' 'Comedy,Drama,Musical'
 'Comedy,Family,Romance' 'Biography,Drama,Family' 'Drama,Fantasy,Musical'
 'Adventure,Family' 'Adventure,Comedy,Fantasy' 'Drama,Family,Music'
 'Comedy,Family,Fantasy']


0      3
1      3
2      2
3      3
4      3
      ..
995    3
996    1
997    3
998    2
999    3
Name: Genre, Length: 1000, dtype: int64



                 Movie_Title                     Genre  Number_of_Genres
0    Guardians of the Galaxy   Action,Adventure,Sci-Fi                 3
1                 Prometheus  Adventure,Mystery,Sci-Fi                 3
2                      Split           Horror,Thriller                 2
3                       Sing   Animation,Comedy,Family                 3
4              Suicide Squad  Action,Adventure,Fantasy                 3
..                       ...                       ...               ...
995     Secret in Their Eyes       Crime,Drama,Mystery                 3
996          Hostel: Part II                    Horror                 1
997   Step Up 2: The Streets       Drama,Music,Romance                 3
998             Search Party          Adventure,Comedy                 2
999               Nine Lives     Comedy,Family,Fantasy                 3

[1000 rows x 3 columns]

Rank                  0
Movie_Title           0
Genre                 0
Description           0
Director              0
Actors                0
Year                  0
Runtime (Minutes)     0
Rating                0
Votes                 0
Revenue (Millions)    0
Metascore             0
dtype: int64

          Movie_Title  Rating
54    The Dark Knight     9.0
80          Inception     8.8
117            Dangal     8.8
36       Interstellar     8.6
249  The Intouchables     8.6

Movie with highest and lowest revenue:
                                   Movie_Title  Revenue (Millions)
50  Star Wars: Episode VII - The Force Awakens              936.63

Movie with highest and lowest revenue:
          Movie_Title  Revenue (Millions)
231  A Kind of Murder                 0.0

Average rating by Director:

Director
Aamir Khan             8.50
Abdellatif Kechiche    7.80
Adam Leon              6.50
Adam McKay             7.00
Adam Shankman          6.30
                       ...
Xavier Dolan           7.55
Yimou Zhang            6.10
Yorgos Lanthimos       7.20
Zack Snyder            7.04
Zackary Adler          5.10
Name: Rating, Length: 644, dtype: float64

Movies per year:

Year
2006     44
2007     53
2008     52
2009     51
2010     60
2011     63
2012     64
2013     91
2014     98
2015    127
2016    297
Name: Movie_Title, dtype: int64

Movies with rating > 8 & revenue > 100M:

                                      Movie_Title  Rating  Revenue (Millions)
0                         Guardians of the Galaxy     8.1              333.13
6                                      La La Land     8.3              151.06
36                                   Interstellar     8.6              187.99
50     Star Wars: Episode VII - The Force Awakens     8.1              936.63
54                                The Dark Knight     9.0              533.32
67                             Mad Max: Fury Road     8.1              153.63
74                                       Zootopia     8.1              341.26
76                                   The Avengers     8.1              623.28
77                           Inglourious Basterds     8.3              120.52
80                                      Inception     8.8              292.57
82                        The Wolf of Wall Street     8.2              116.87
83                                      Gone Girl     8.1              167.74
92                                       The Help     8.1              169.71
99                                   The Departed     8.5              132.37
114  Harry Potter and the Deathly Hallows: Part 2     8.1              380.96
124                         The Dark Knight Rises     8.5              448.13
138                                Shutter Island     8.1              127.97
144                              Django Unchained     8.4              162.80
241                                    Inside Out     8.2              356.45
427                          The Bourne Ultimatum     8.1              227.14
499                                            Up     8.3              292.98
634                                        WALL·E     8.4              223.81
645                                   Gran Torino     8.2              148.09
688                                   Toy Story 3     8.3              414.98
772                      How to Train Your Dragon     8.1              217.39

Group by Director: avg Rating, Revenue:

                     Rating  Revenue (Millions)
Director
Aamir Khan             8.50            1.200000
Abdellatif Kechiche    7.80            2.200000
Adam Leon              6.50           82.956376
Adam McKay             7.00          109.535000
Adam Shankman          6.30           78.665000
...                     ...                 ...
Xavier Dolan           7.55           43.223188
Yimou Zhang            6.10           45.130000
Yorgos Lanthimos       7.20            4.405000
Zack Snyder            7.04          195.148000
Zackary Adler          5.10            6.530000

[644 rows x 2 columns]

In [33]:
# Shape
print("Shape of dataset:")
print(df.shape)
print("\n")

# First 5 rows
print("\nFirst 5 rows:")
print(df.head())
print("\n")

# Column names
print("\nColumn names:")
print(df.columns)
print("\n")

# Data types
print("\nData types:")
print(df.dtypes)
print("\n")

# Missing values
print("\nMissing values:")
print(df.isnull().sum())
print("\n")

# 4) To Check and remove duplicates.

# Check number of duplicate rows
print("\nNumber of duplicate rows:")
print(df.duplicated().sum())
print("\n")

# Remove duplicates
df = df.drop_duplicates()

print("\nShape after removing duplicates:")
print(df.shape)
print("\n")

# 5) Rename column "Title" to "Movie_Title"

df.rename(columns={'Title': 'Movie_Title'}, inplace=True)

print("\nColumns after renaming:")
print(df.columns)
print("\n")

# 6) Get unique genres.

print("\nUnique Genres:")
print(df['Genre'].unique())
print("\n")

# 7) Extract number of genres per movie

print(df['Genre'].str.split(',').str.len())
print("\n")
print()

#OR

print(df[['Movie_Title', 'Genre']].assign(
    Number_of_Genres=df['Genre'].str.split(',').str.len()))
print()

# 8)  Handle missing values in 'Revenue (Millions)' and 'Metascore.

df['Revenue (Millions)'] = df['Revenue (Millions)'].fillna(df['Revenue (Millions)'].mean()) # fillna() - Use to replace/handle missing values.

df['Metascore'] = df['Metascore'].fillna(df['Metascore'].mean())

print(df.isnull().sum())
print()

# 9) Top 5 movies by Rating.

top5 = df.sort_values('Rating', ascending=False).head(5)

print(top5[['Movie_Title', 'Rating']])

print()

# 10) Movie with highest revenue

highest = df.sort_values('Revenue (Millions)', ascending=False).head(1)
print("Movie with highest and lowest revenue: ")

print(highest[['Movie_Title', 'Revenue (Millions)']])
print()

# Movie with lowest revenue.

lowest = df.sort_values('Revenue (Millions)').head(1)
print("Movie with highest and lowest revenue: ")

print(lowest[['Movie_Title', 'Revenue (Millions)']])
print()

#11) Average rating by Director.

avg_rating = df.groupby('Director')['Rating'].mean()
print("Average rating by Director: ")
print()
print(avg_rating)
print()

#12) Movies per year.

movies_year = df.groupby('Year')['Movie_Title'].count()
print("Movies per year: ")
print()
print(movies_year)
print()

#13)  Movies with rating > 8 & revenue > 100M

result = df[(df['Rating'] > 8) & (df['Revenue (Millions)'] > 100)]
print("Movies with rating > 8 & revenue > 100M: ")
print()
print(result[['Movie_Title', 'Rating', 'Revenue (Millions)']])
print()

#14) Group by Director: avg Rating, Revenue.

director_group = df.groupby('Director')[['Rating', 'Revenue (Millions)']].mean()
print("Group by Director: avg Rating, Revenue: ")
print()
print(director_group)
print()

#15)  Group by Year: count, avg Rating.

year_group = df.groupby('Year')[['Rating']].agg(['count', 'mean']) # Performs multiple calculation on 'Rating' column.
print("Group by Year: count, avg Rating: ")
print()
print(year_group)
print()

#16) Create a new column Profitability:
# a) Revenue divided by Duration.

df['Profitability'] = df['Revenue (Millions)'] / df['Runtime (Minutes)']
print("New column Profitability: ")
print()
print(df[['Movie_Title', 'Profitability']])
print()

# b) Find top 10 most profitable movies.

top10 = df.sort_values('Profitability', ascending=False).head(10)
print("Top 10 most profitable movies: ")
print()
print(top10[['Movie_Title', 'Profitability']])
print()

#17) Create a column that categorizes movies by rating:
# a) Rating < 6: Poor.
# b) 6 ≤ Rating < 7.5: Average.
# c) Rating ≥ 7.5: Excellent.

df['Rating_Category'] = pd.cut(df['Rating'], bins=[0, 6, 7.5, float('inf')],
                                labels=['Poor', 'Average', 'Excellent'])
print("Rating_Category: ")
print()
print(df[['Movie_Title', 'Rating', 'Rating_Category']])
print()

#18) Create a custom function to score movies based on:
# i) Apply row['Rating'] * 10 + row['Revenue (Millions)'] as High score.
# Apply a function to dataset to assign the score.

def score_movie(row):
    return row['Rating'] * 10 + row['Revenue (Millions)']

df['High_Score'] = df.apply(score_movie, axis=1)
print("High_Score: ")
print()
print(df[['Movie_Title', 'Rating', 'Revenue (Millions)', 'High_Score']])
print()

#

Shape of dataset:
(1000, 15)



First 5 rows:
   Rank              Movie_Title                     Genre  \
0     1  Guardians of the Galaxy   Action,Adventure,Sci-Fi
1     2               Prometheus  Adventure,Mystery,Sci-Fi
2     3                    Split           Horror,Thriller
3     4                     Sing   Animation,Comedy,Family
4     5            Suicide Squad  Action,Adventure,Fantasy

                                         Description              Director  \
0  A group of intergalactic criminals are forced ...            James Gunn
1  Following clues to the origin of mankind, a te...          Ridley Scott
2  Three girls are kidnapped by a man with a diag...    M. Night Shyamalan
3  In a city of humanoid animals, a hustling thea...  Christophe Lourdelet
4  A secret government agency recruits some of th...            David Ayer

                                              Actors  Year  Runtime (Minutes)  \
0  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014                121
1  Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012                124
2  James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016                117
3  Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016                108
4  Will Smith, Jared Leto, Margot Robbie, Viola D...  2016                123

   Rating   Votes  Revenue (Millions)  Metascore  Profitability  \
0     8.1  757074              333.13       76.0       2.753140
1     7.0  485820              126.46       65.0       1.019839
2     7.3  157606              138.12       62.0       1.180513
3     7.2   60545              270.32       59.0       2.502963
4     6.2  393727              325.02       40.0       2.642439

  Rating_Category  High_Score
0       Excellent      414.13
1         Average      196.46
2         Average      211.12
3         Average      342.32
4         Average      387.02



Column names:
Index(['Rank', 'Movie_Title', 'Genre', 'Description', 'Director', 'Actors',
       'Year', 'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore', 'Profitability', 'Rating_Category', 'High_Score'],
      dtype='object')



Data types:
Rank                     int64
Movie_Title             object
Genre                   object
Description             object
Director                object
Actors                  object
Year                     int64
Runtime (Minutes)        int64
Rating                 float64
Votes                    int64
Revenue (Millions)     float64
Metascore              float64
Profitability          float64
Rating_Category       category
High_Score             float64
dtype: object



Missing values:
Rank                  0
Movie_Title           0
Genre                 0
Description           0
Director              0
Actors                0
Year                  0
Runtime (Minutes)     0
Rating                0
Votes                 0
Revenue (Millions)    0
Metascore             0
Profitability         0
Rating_Category       0
High_Score            0
dtype: int64



Number of duplicate rows:
0



Shape after removing duplicates:
(1000, 15)



Columns after renaming:
Index(['Rank', 'Movie_Title', 'Genre', 'Description', 'Director', 'Actors',
       'Year', 'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore', 'Profitability', 'Rating_Category', 'High_Score'],
      dtype='object')



Unique Genres:
['Action,Adventure,Sci-Fi' 'Adventure,Mystery,Sci-Fi' 'Horror,Thriller'
 'Animation,Comedy,Family' 'Action,Adventure,Fantasy' 'Comedy,Drama,Music'
 'Comedy' 'Action,Adventure,Biography' 'Adventure,Drama,Romance'
 'Adventure,Family,Fantasy' 'Biography,Drama,History'
 'Animation,Adventure,Comedy' 'Action,Comedy,Drama' 'Action,Thriller'
 'Biography,Drama' 'Drama,Mystery,Sci-Fi' 'Adventure,Drama,Thriller'
 'Drama' 'Crime,Drama,Horror' 'Action,Adventure,Drama' 'Drama,Thriller'
 'Action,Adventure,Comedy' 'Action,Horror,Sci-Fi' 'Adventure,Drama,Sci-Fi'
 'Action,Adventure,Western' 'Comedy,Drama' 'Horror'
 'Adventure,Drama,Fantasy' 'Action,Crime,Thriller' 'Action,Crime,Drama'
 'Adventure,Drama,History' 'Crime,Horror,Thriller' 'Drama,Romance'
 'Comedy,Drama,Romance' 'Horror,Mystery,Thriller' 'Crime,Drama,Mystery'
 'Drama,Romance,Thriller' 'Drama,History,Thriller' 'Action,Drama,Thriller'
 'Drama,History' 'Action,Drama,Romance' 'Drama,Fantasy' 'Action,Sci-Fi'
 'Adventure,Drama,War' 'Action,Comedy,Fantasy' 'Biography,Comedy,Crime'
 'Crime,Drama' 'Comedy,Crime,Drama' 'Action,Comedy,Crime'
 'Animation,Drama,Fantasy' 'Horror,Mystery,Sci-Fi'
 'Drama,Mystery,Thriller' 'Crime,Drama,Thriller' 'Biography,Crime,Drama'
 'Crime,Mystery,Thriller' 'Action,Horror,Thriller' 'Romance,Sci-Fi'
 'Action,Fantasy,War' 'Action,Biography,Drama' 'Drama,Horror,Mystery'
 'Adventure,Drama,Family' 'Adventure,Comedy,Romance' 'Action'
 'Adventure,Crime,Mystery' 'Comedy,Family,Musical'
 'Adventure,Comedy,Drama' 'Drama,Horror,Thriller' 'Drama,Music'
 'Mystery,Thriller' 'Mystery,Thriller,Western' 'Comedy,Family'
 'Biography,Comedy,Drama' 'Drama,Western' 'Drama,Mystery,Romance'
 'Action,Drama,Mystery' 'Action,Adventure,Crime'
 'Adventure,Sci-Fi,Thriller' 'Action,Comedy,Mystery' 'Thriller,War'
 'Action,Adventure,Thriller' 'Drama,Fantasy,Romance'
 'Action,Drama,History' 'Animation,Adventure,Family' 'Adventure,Horror'
 'Drama,Romance,Sci-Fi' 'Action,Adventure,Family' 'Action,Comedy'
 'Comedy,Romance' 'Horror,Mystery' 'Drama,Family,Fantasy' 'Sci-Fi'
 'Drama,War' 'Drama,Fantasy,Horror' 'Crime,Drama,History'
 'Horror,Sci-Fi,Thriller' 'Action,Drama,Sport' 'Adventure,Biography,Drama'
 'Biography,Drama,Thriller' 'Action,Adventure,Mystery' 'Drama,Horror'
 'Comedy,Crime' 'Drama,Fantasy,War' 'Action,Adventure,Romance'
 'Action,Drama,War' 'Drama,Musical,Romance' 'Drama,Sci-Fi,Thriller'
 'Action,Drama,Sci-Fi' 'Drama,Sci-Fi' 'Adventure,Fantasy' 'Thriller'
 'Biography,Drama,Romance' 'Action,Adventure' 'Action,Fantasy'
 'Action,Drama,Horror' 'Comedy,Music,Romance' 'Biography,Drama,Sport'
 'Action,Horror' 'Comedy,Horror,Thriller' 'Crime,Drama,Music'
 'Action,Sci-Fi,Thriller' 'Drama,Horror,Sci-Fi' 'Drama,Sport'
 'Comedy,Horror' 'Comedy,Fantasy,Romance' 'Comedy,Fantasy'
 'Comedy,Drama,Fantasy' 'Adventure,Comedy,Horror' 'Comedy,Mystery'
 'Action,Mystery,Sci-Fi' 'Action,Crime,Fantasy' 'Comedy,Fantasy,Horror'
 'Animation,Action,Adventure' 'Action,Comedy,Family' 'Comedy,Sci-Fi'
 'Action,Biography,Crime' 'Adventure,Comedy' 'Comedy,Music'
 'Comedy,Drama,Horror' 'Action,Horror,Romance' 'Action,Drama,Fantasy'
 'Action,Mystery,Thriller' 'Action,Adventure,Horror'
 'Animation,Family,Fantasy' 'Adventure,Horror,Mystery'
 'Action,Horror,Mystery' 'Adventure,Comedy,Family' 'Action,Crime,Mystery'
 'Comedy,Drama,Family' 'Action,Crime,Sport' 'Mystery,Sci-Fi,Thriller'
 'Sci-Fi,Thriller' 'Adventure,Drama,Horror' 'Biography,History,Thriller'
 'Adventure,Comedy,Sci-Fi' 'Fantasy,Horror' 'Action,Fantasy,Thriller'
 'Comedy,Romance,Sport' 'Animation,Action,Comedy' 'Drama,Fantasy,Thriller'
 'Action,Comedy,Romance' 'Action,Fantasy,Horror' 'Mystery,Romance,Sci-Fi'
 'Comedy,Drama,Thriller' 'Comedy,Western' 'Drama,History,War'
 'Fantasy,Horror,Thriller' 'Drama,Horror,Musical' 'Drama,Family'
 'Romance,Sci-Fi,Thriller' 'Animation,Fantasy' 'Drama,Mystery,War'
 'Action,Drama,Family' 'Adventure,Drama,Western' 'Drama,Music,Romance'
 'Comedy,Romance,Western' 'Adventure,Drama' 'Drama,Thriller,War'
 'Drama,Fantasy,Mystery' 'Comedy,Crime,Thriller' 'Animation,Comedy,Drama'
 'Action,Comedy,Sci-Fi' 'Drama,Romance,War' 'Adventure,Fantasy,Mystery'
 'Mystery,Romance,Thriller' 'Biography,Drama,Mystery'
 'Animation,Drama,Romance' 'Comedy,Horror,Romance' 'Action,Thriller,War'
 'Action,Comedy,Horror' 'Action,Crime,Sci-Fi' 'Crime,Thriller'
 'Comedy,Horror,Sci-Fi' 'Crime,Drama,Fantasy' 'Drama,Fantasy,Music'
 'Action,Comedy,Sport' 'Fantasy,Mystery,Thriller' 'Adventure'
 'Adventure,Biography' 'Adventure,Biography,Crime' 'Comedy,Drama,Musical'
 'Comedy,Family,Romance' 'Biography,Drama,Family' 'Drama,Fantasy,Musical'
 'Adventure,Family' 'Adventure,Comedy,Fantasy' 'Drama,Family,Music'
 'Comedy,Family,Fantasy']


0      3
1      3
2      2
3      3
4      3
      ..
995    3
996    1
997    3
998    2
999    3
Name: Genre, Length: 1000, dtype: int64



                 Movie_Title                     Genre  Number_of_Genres
0    Guardians of the Galaxy   Action,Adventure,Sci-Fi                 3
1                 Prometheus  Adventure,Mystery,Sci-Fi                 3
2                      Split           Horror,Thriller                 2
3                       Sing   Animation,Comedy,Family                 3
4              Suicide Squad  Action,Adventure,Fantasy                 3
..                       ...                       ...               ...
995     Secret in Their Eyes       Crime,Drama,Mystery                 3
996          Hostel: Part II                    Horror                 1
997   Step Up 2: The Streets       Drama,Music,Romance                 3
998             Search Party          Adventure,Comedy                 2
999               Nine Lives     Comedy,Family,Fantasy                 3

[1000 rows x 3 columns]

Rank                  0
Movie_Title           0
Genre                 0
Description           0
Director              0
Actors                0
Year                  0
Runtime (Minutes)     0
Rating                0
Votes                 0
Revenue (Millions)    0
Metascore             0
Profitability         0
Rating_Category       0
High_Score            0
dtype: int64

          Movie_Title  Rating
54    The Dark Knight     9.0
80          Inception     8.8
117            Dangal     8.8
36       Interstellar     8.6
249  The Intouchables     8.6

Movie with highest and lowest revenue:
                                   Movie_Title  Revenue (Millions)
50  Star Wars: Episode VII - The Force Awakens              936.63

Movie with highest and lowest revenue:
          Movie_Title  Revenue (Millions)
231  A Kind of Murder                 0.0

Average rating by Director:

Director
Aamir Khan             8.50
Abdellatif Kechiche    7.80
Adam Leon              6.50
Adam McKay             7.00
Adam Shankman          6.30
                       ...
Xavier Dolan           7.55
Yimou Zhang            6.10
Yorgos Lanthimos       7.20
Zack Snyder            7.04
Zackary Adler          5.10
Name: Rating, Length: 644, dtype: float64

Movies per year:

Year
2006     44
2007     53
2008     52
2009     51
2010     60
2011     63
2012     64
2013     91
2014     98
2015    127
2016    297
Name: Movie_Title, dtype: int64

Movies with rating > 8 & revenue > 100M:

                                      Movie_Title  Rating  Revenue (Millions)
0                         Guardians of the Galaxy     8.1              333.13
6                                      La La Land     8.3              151.06
36                                   Interstellar     8.6              187.99
50     Star Wars: Episode VII - The Force Awakens     8.1              936.63
54                                The Dark Knight     9.0              533.32
67                             Mad Max: Fury Road     8.1              153.63
74                                       Zootopia     8.1              341.26
76                                   The Avengers     8.1              623.28
77                           Inglourious Basterds     8.3              120.52
80                                      Inception     8.8              292.57
82                        The Wolf of Wall Street     8.2              116.87
83                                      Gone Girl     8.1              167.74
92                                       The Help     8.1              169.71
99                                   The Departed     8.5              132.37
114  Harry Potter and the Deathly Hallows: Part 2     8.1              380.96
124                         The Dark Knight Rises     8.5              448.13
138                                Shutter Island     8.1              127.97
144                              Django Unchained     8.4              162.80
241                                    Inside Out     8.2              356.45
427                          The Bourne Ultimatum     8.1              227.14
499                                            Up     8.3              292.98
634                                        WALL·E     8.4              223.81
645                                   Gran Torino     8.2              148.09
688                                   Toy Story 3     8.3              414.98
772                      How to Train Your Dragon     8.1              217.39

Group by Director: avg Rating, Revenue:

                     Rating  Revenue (Millions)
Director
Aamir Khan             8.50            1.200000
Abdellatif Kechiche    7.80            2.200000
Adam Leon              6.50           82.956376
Adam McKay             7.00          109.535000
Adam Shankman          6.30           78.665000
...                     ...                 ...
Xavier Dolan           7.55           43.223188
Yimou Zhang            6.10           45.130000
Yorgos Lanthimos       7.20            4.405000
Zack Snyder            7.04          195.148000
Zackary Adler          5.10            6.530000

[644 rows x 2 columns]

Group by Year: count, avg Rating:

     Rating
      count      mean
Year
2006     44  7.125000
2007     53  7.133962
2008     52  6.784615
2009     51  6.960784
2010     60  6.826667
2011     63  6.838095
2012     64  6.925000
2013     91  6.812088
2014     98  6.837755
2015    127  6.602362
2016    297  6.436700

New column Profitability:

                 Movie_Title  Profitability
0    Guardians of the Galaxy       2.753140
1                 Prometheus       1.019839
2                      Split       1.180513
3                       Sing       2.502963
4              Suicide Squad       2.642439
..                       ...            ...
995     Secret in Their Eyes       0.747355
996          Hostel: Part II       0.186596
997   Step Up 2: The Streets       0.591939
998             Search Party       0.892004
999               Nine Lives       0.225747

[1000 rows x 2 columns]

Top 10 most profitable movies:

                                    Movie_Title  Profitability
50   Star Wars: Episode VII - The Force Awakens       6.886985
85                               Jurassic World       5.259516
119                                Finding Dory       5.013299
87                                       Avatar       4.694506
76                                 The Avengers       4.358601
15                      The Secret Life of Pets       4.233448
688                                 Toy Story 3       4.028932
12                                    Rogue One       4.001278
174                                      Frozen       3.928824
797                             Despicable Me 2       3.755612

Rating_Category:

                 Movie_Title  Rating Rating_Category
0    Guardians of the Galaxy     8.1       Excellent
1                 Prometheus     7.0         Average
2                      Split     7.3         Average
3                       Sing     7.2         Average
4              Suicide Squad     6.2         Average
..                       ...     ...             ...
995     Secret in Their Eyes     6.2         Average
996          Hostel: Part II     5.5            Poor
997   Step Up 2: The Streets     6.2         Average
998             Search Party     5.6            Poor
999               Nine Lives     5.3            Poor

[1000 rows x 3 columns]

High_Score:

                 Movie_Title  Rating  Revenue (Millions)  High_Score
0    Guardians of the Galaxy     8.1          333.130000  414.130000
1                 Prometheus     7.0          126.460000  196.460000
2                      Split     7.3          138.120000  211.120000
3                       Sing     7.2          270.320000  342.320000
4              Suicide Squad     6.2          325.020000  387.020000
..                       ...     ...                 ...         ...
995     Secret in Their Eyes     6.2           82.956376  144.956376
996          Hostel: Part II     5.5           17.540000   72.540000
997   Step Up 2: The Streets     6.2           58.010000  120.010000
998             Search Party     5.6           82.956376  138.956376
999               Nine Lives     5.3           19.640000   72.640000

[1000 rows x 4 columns]

In [34]:
df

,Rank,Movie_Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,Profitability,Rating_Category,High_Score
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.130000,76.0,2.753140,Excellent,414.130000
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.460000,65.0,1.019839,Average,196.460000
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.120000,62.0,1.180513,Average,211.120000
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.320000,59.0,2.502963,Average,342.320000
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.020000,40.0,2.642439,Average,387.020000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,82.956376,45.0,0.747355,Average,144.956376
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.540000,46.0,0.186596,Poor,72.540000
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.010000,50.0,0.591939,Average,120.010000
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,82.956376,22.0,0.892004,Poor,138.956376
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.640000,11.0,0.225747,Poor,72.640000